// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDEquipmentID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDEquipmentID));
        
        string IMigrationMetadata.Id
        {
            get { return "201811200427316_ADDEquipmentID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
