//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 異常警示 的當地語系化字串。
        /// </summary>
        internal static string Abnormal {
            get {
                return ResourceManager.GetString("Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電池 的當地語系化字串。
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告資訊 的當地語系化字串。
        /// </summary>
        internal static string Bulletin {
            get {
                return ResourceManager.GetString("Bulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 充電樁 的當地語系化字串。
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行控中心 的當地語系化字串。
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增單位 的當地語系化字串。
        /// </summary>
        internal static string CreateOrgin {
            get {
                return ResourceManager.GetString("CreateOrgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發電機 的當地語系化字串。
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 市電 的當地語系化字串。
        /// </summary>
        internal static string GridPower {
            get {
                return ResourceManager.GetString("GridPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 歷史資訊 的當地語系化字串。
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 即時資訊 的當地語系化字串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 逆變器 的當地語系化字串。
        /// </summary>
        internal static string Inverters {
            get {
                return ResourceManager.GetString("Inverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 負載 的當地語系化字串。
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 屏東防災微電網 的當地語系化字串。
        /// </summary>
        internal static string LogoName {
            get {
                return ResourceManager.GetString("LogoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 維護管理 的當地語系化字串。
        /// </summary>
        internal static string Maintain {
            get {
                return ResourceManager.GetString("Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QR碼 的當地語系化字串。
        /// </summary>
        internal static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 太陽能 的當地語系化字串。
        /// </summary>
        internal static string Solar {
            get {
                return ResourceManager.GetString("Solar", resourceCulture);
            }
        }
    }
}
